#!/usr/bin/env python3
"""Netra Host Agent CLI for easy install/integration with Kakveda."""

from __future__ import annotations

import argparse
import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

from dotenv import load_dotenv


def _default_env_path() -> Path:
    cfg = os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
    return Path(cfg) / "kakveda-netra" / ".env"


def _env_line(key: str, value: str) -> str:
    return f"{key}={value}\n"


def _local_ip() -> str:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))
        return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"
    finally:
        s.close()


def _build_env_template(hostname: str) -> str:
    ip = _local_ip()
    lines = [
        "# Netra Host Agent configuration",
        "# Generated by: kakveda-netra init",
        "",
        _env_line("AGENT_NAME", f"netra-{hostname}").strip(),
        _env_line("AGENT_APP_ID", "host-infra").strip(),
        _env_line("AGENT_VERSION", "1.0.0").strip(),
        _env_line("AGENT_BASE_URL", f"http://{ip}:8120").strip(),
        "",
        _env_line("DASHBOARD_URL", "http://localhost:8110").strip(),
        _env_line("DASHBOARD_API_KEY", "replace-with-project-api-key").strip(),
        _env_line("KAKVEDA_EVENT_BUS_URL", "http://localhost:8100/publish").strip(),
        "",
        _env_line("AUTO_REGISTER", "true").strip(),
        _env_line("ENABLE_HEARTBEAT", "true").strip(),
        _env_line("HEARTBEAT_INTERVAL", "15").strip(),
        "",
        _env_line("ENABLE_INFRA_METRICS", "true").strip(),
        _env_line("INFRA_COLLECTION_INTERVAL_SEC", "5").strip(),
        _env_line("INFRA_METRICS_TOPIC", "infra.metrics").strip(),
        _env_line("INFRA_MAX_INTERFACES", "50").strip(),
        _env_line("INFRA_MAX_CONTAINERS", "100").strip(),
        _env_line("INFRA_MAX_PARTITIONS", "20").strip(),
        "",
        _env_line("INFRA_METRICS_ENDPOINT_ENABLED", "true").strip(),
        _env_line("INFRA_METRICS_ENDPOINT_HOST", "0.0.0.0").strip(),
        _env_line("INFRA_METRICS_ENDPOINT_PORT", "9320").strip(),
        "",
    ]
    return "\n".join(lines) + "\n"


def cmd_init(args: argparse.Namespace) -> int:
    path = Path(args.env_file).expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not args.force:
        print(f"[aankh] env file already exists: {path}")
        print("[aankh] use --force to overwrite")
        return 1

    hostname = socket.gethostname()
    content = _build_env_template(hostname=hostname)
    path.write_text(content, encoding="utf-8")
    print(f"[netra] wrote config: {path}")
    print("[netra] next: update DASHBOARD_API_KEY in this file, then run `kakveda-netra run`")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    from .agent import KakvedaAgent

    env_path = Path(args.env_file).expanduser().resolve()
    if env_path.exists():
        load_dotenv(dotenv_path=env_path, override=False)
        print(f"[aankh] loaded env: {env_path}")
    else:
        print(f"[netra] env file not found: {env_path}")
        print("[netra] run `kakveda-netra init` first")
        return 1

    api_key = (os.environ.get("DASHBOARD_API_KEY") or "").strip()
    if not api_key or api_key == "replace-with-project-api-key":
        print("[netra] invalid DASHBOARD_API_KEY in env file")
        return 1

    capabilities = ["infra.metrics", "host.monitoring"]
    agent = KakvedaAgent(capabilities=capabilities)
    print(
        "[netra] started "
        f"name={agent.agent_name} app_id={agent.app_id} "
        f"dashboard={agent.dashboard_url} interval={agent.infra_interval_sec}s"
    )
    print("[netra] press Ctrl+C to stop")

    try:
        while True:
            time.sleep(60)
    except KeyboardInterrupt:
        print("\n[netra] stopped")
    return 0


def _service_unit_text(exec_start: str, env_file: str) -> str:
    return (
        "[Unit]\n"
        "Description=Kakveda Netra Host Agent\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n\n"
        "[Service]\n"
        "Type=simple\n"
        f"EnvironmentFile={env_file}\n"
        f"ExecStart={exec_start}\n"
        "Restart=always\n"
        "RestartSec=5\n"
        "WorkingDirectory=/\n\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def _run_cmd(cmd: list[str]) -> tuple[int, str]:
    try:
        proc = subprocess.run(cmd, text=True, capture_output=True, check=False)
        out = (proc.stdout or "") + (proc.stderr or "")
        return int(proc.returncode), out.strip()
    except Exception as exc:
        return 1, str(exc)


def cmd_install_service(args: argparse.Namespace) -> int:
    env_path = str(Path(args.env_file).expanduser().resolve())
    unit_name = "kakveda-netra.service"
    exe = sys.executable
    exec_start = f"{exe} -m kakveda_sdk.aankh_agent_cli run --env-file {env_path}"
    unit_text = _service_unit_text(exec_start=exec_start, env_file=env_path)

    scope = args.scope
    if scope == "user":
        user_dir = Path.home() / ".config" / "systemd" / "user"
        user_dir.mkdir(parents=True, exist_ok=True)
        unit_path = user_dir / unit_name
        unit_path.write_text(unit_text.replace("multi-user.target", "default.target"), encoding="utf-8")
        print(f"[netra] wrote user unit: {unit_path}")

        for cmd in (
            ["systemctl", "--user", "daemon-reload"],
            ["systemctl", "--user", "enable", "--now", unit_name],
        ):
            code, out = _run_cmd(cmd)
            if code != 0:
                print(f"[netra] command failed: {' '.join(cmd)}")
                if out:
                    print(out)
                print("[netra] hint: run `loginctl enable-linger $USER` for boot-time user service")
                return 1
        print("[netra] user service installed and started")
        print("[netra] status: systemctl --user status kakveda-netra.service")
        return 0

    # system scope
    system_path = Path("/etc/systemd/system") / unit_name
    write_cmd = f"cat > {system_path} <<'EOF'\n{unit_text}EOF"
    cmds = [
        ["sh", "-c", write_cmd],
        ["systemctl", "daemon-reload"],
        ["systemctl", "enable", "--now", unit_name],
    ]
    if os.geteuid() != 0:
        if not shutil.which("sudo"):
            print("[netra] sudo not found; cannot install system service")
            print("[netra] retry with --scope user, or run as root")
            return 1
        cmds = [["sudo"] + c for c in cmds]

    for cmd in cmds:
        code, out = _run_cmd(cmd)
        if code != 0:
            print(f"[netra] command failed: {' '.join(cmd)}")
            if out:
                print(out)
            print("[netra] manual fallback:")
            print(f"  1) write unit to {system_path}")
            print("  2) sudo systemctl daemon-reload")
            print("  3) sudo systemctl enable --now kakveda-netra.service")
            return 1
    print("[netra] system service installed and started")
    print("[netra] status: sudo systemctl status kakveda-netra.service")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    unit_name = "kakveda-netra.service"
    scope = args.scope
    if scope == "user":
        cmds = [
            ["systemctl", "--user", "is-enabled", unit_name],
            ["systemctl", "--user", "is-active", unit_name],
            ["systemctl", "--user", "status", "--no-pager", unit_name],
        ]
    else:
        if os.geteuid() == 0:
            cmds = [
                ["systemctl", "is-enabled", unit_name],
                ["systemctl", "is-active", unit_name],
                ["systemctl", "status", "--no-pager", unit_name],
            ]
        else:
            cmds = [
                ["sudo", "systemctl", "is-enabled", unit_name],
                ["sudo", "systemctl", "is-active", unit_name],
                ["sudo", "systemctl", "status", "--no-pager", unit_name],
            ]

    for cmd in cmds:
        code, out = _run_cmd(cmd)
        print(f"$ {' '.join(cmd)}")
        if out:
            print(out)
        if code != 0 and cmd[-1] != unit_name:
            return 1
    return 0


def cmd_uninstall_service(args: argparse.Namespace) -> int:
    unit_name = "kakveda-aankh.service"
    scope = args.scope

    if scope == "user":
        unit_path = Path.home() / ".config" / "systemd" / "user" / unit_name
        for cmd in (
            ["systemctl", "--user", "disable", "--now", unit_name],
            ["systemctl", "--user", "daemon-reload"],
        ):
            code, out = _run_cmd(cmd)
            if code != 0:
                print(f"[netra] command failed: {' '.join(cmd)}")
                if out:
                    print(out)
        try:
            if unit_path.exists():
                unit_path.unlink()
                print(f"[netra] removed user unit: {unit_path}")
        except Exception as exc:
            print(f"[netra] failed to remove {unit_path}: {exc}")
            return 1
        print("[netra] user service uninstalled")
        return 0

    unit_path = Path("/etc/systemd/system") / unit_name
    remove_cmd = f"rm -f {unit_path}"
    cmds = [
        ["systemctl", "disable", "--now", unit_name],
        ["sh", "-c", remove_cmd],
        ["systemctl", "daemon-reload"],
    ]
    if os.geteuid() != 0:
        if not shutil.which("sudo"):
            print("[netra] sudo not found; cannot uninstall system service")
            return 1
        cmds = [["sudo"] + c for c in cmds]

    for cmd in cmds:
        code, out = _run_cmd(cmd)
        if code != 0:
            print(f"[netra] command failed: {' '.join(cmd)}")
            if out:
                print(out)
    print("[netra] system service uninstalled")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Netra Host Agent CLI")
    sub = p.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Create default .env config")
    p_init.add_argument("--env-file", default=str(_default_env_path()), help="Path for .env file")
    p_init.add_argument("--force", action="store_true", help="Overwrite existing file")
    p_init.set_defaults(func=cmd_init)

    p_run = sub.add_parser("run", help="Run Netra host agent")
    p_run.add_argument("--env-file", default=str(_default_env_path()), help="Path to .env file")
    p_run.set_defaults(func=cmd_run)

    p_service = sub.add_parser("install-service", help="Install and start systemd service")
    p_service.add_argument("--env-file", default=str(_default_env_path()), help="Path to .env file")
    p_service.add_argument(
        "--scope",
        choices=["system", "user"],
        default="system",
        help="Service scope: system (boot-wide) or user (no sudo).",
    )
    p_service.set_defaults(func=cmd_install_service)

    p_status = sub.add_parser("status", help="Show service status")
    p_status.add_argument(
        "--scope",
        choices=["system", "user"],
        default="system",
        help="Service scope to inspect.",
    )
    p_status.set_defaults(func=cmd_status)

    p_uninstall = sub.add_parser("uninstall-service", help="Disable and remove systemd service")
    p_uninstall.add_argument(
        "--scope",
        choices=["system", "user"],
        default="system",
        help="Service scope to uninstall.",
    )
    p_uninstall.set_defaults(func=cmd_uninstall_service)

    return p


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    code = args.func(args)
    sys.exit(code)


if __name__ == "__main__":
    main()
