from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional


@dataclass(frozen=True)
class SetupAnswers:
    # Dashboard storage
    dashboard_db_url: str

    # Secrets
    dashboard_jwt_secret: str

    # Optional redis
    redis_url: Optional[str]

    # Optional OTel
    otel_enabled: bool
    otel_exporter_otlp_endpoint: Optional[str]

    # Optional model provider (non-ollama)
    model_provider: str  # "ollama" | "openai" | "other"
    model_api_key: Optional[str]
    model_base_url: Optional[str]
    model_name: Optional[str]

    # Compose selection
    use_prod_compose: bool
    # SMTP config
    smtp_host: Optional[str] = None
    smtp_port: Optional[str] = None
    smtp_user: Optional[str] = None
    smtp_pass: Optional[str] = None
    smtp_from: Optional[str] = None
    smtp_tls: Optional[bool] = None


def env_dict_from_answers(a: SetupAnswers) -> Dict[str, str]:
    env: Dict[str, str] = {}

    env["DASHBOARD_DB_URL"] = a.dashboard_db_url
    env["DASHBOARD_JWT_SECRET"] = a.dashboard_jwt_secret

    if a.redis_url:
        env["KAKVEDA_REDIS_URL"] = a.redis_url

    env["KAKVEDA_OTEL_ENABLED"] = "1" if a.otel_enabled else "0"
    if a.otel_exporter_otlp_endpoint:
        env["OTEL_EXPORTER_OTLP_ENDPOINT"] = a.otel_exporter_otlp_endpoint

    # Model provider settings are best-effort: services may or may not consume these.
    env["KAKVEDA_MODEL_PROVIDER"] = a.model_provider
    if a.model_api_key:
        env["KAKVEDA_MODEL_API_KEY"] = a.model_api_key
    if a.model_base_url:
        env["KAKVEDA_MODEL_BASE_URL"] = a.model_base_url
    if a.model_name:
        env["KAKVEDA_MODEL_NAME"] = a.model_name


    # SMTP config
    if a.smtp_host:
        env["SMTP_HOST"] = a.smtp_host
    if a.smtp_port:
        env["SMTP_PORT"] = a.smtp_port
    if a.smtp_user:
        env["SMTP_USER"] = a.smtp_user
    if a.smtp_pass:
        env["SMTP_PASS"] = a.smtp_pass
    if a.smtp_from:
        env["SMTP_FROM"] = a.smtp_from
    if a.smtp_tls is not None:
        env["SMTP_TLS"] = "1" if a.smtp_tls else "0"

    return env


def write_env_file(env_path: Path, env: Dict[str, str]) -> None:
    """Write a .env file in KEY=VALUE format.

    Note: Values are written without quotes. Avoid spaces/newlines.
    """

    lines = []
    lines.append("# Generated by kakveda CLI")

    for key in sorted(env.keys()):
        val = env[key]
        lines.append(f"{key}={val}")

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
